# Generated by Django 4.0.6 on 2022-09-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='avatar_img',
            field=models.ImageField(choices=[('wherenext/images/defualt_profile.png', 'Good'), ('wherenext/images/logo.svg.png', 'Ugly')], default='wherenext/images/defualt_profile.png', upload_to=''),
        ),
    ]
