# Generated by Django 4.0.6 on 2022-09-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_traveler_avatar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='avatar_img',
            field=models.ImageField(default='defualt.png', upload_to='profile_pics'),
        ),
    ]
