# Generated by Django 4.0.6 on 2022-10-04 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_traveler_avatar_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_date', models.DateField()),
                ('return_date', models.DateField()),
                ('budget', models.IntegerField()),
                ('point_of_interest', models.CharField(choices=[('food', 'Food'), ('history', 'History'), ('sport', 'Sport'), ('clubs', 'Night life'), ('shopping', 'Shopping')], max_length=50)),
                ('on_season', models.BooleanField(default=False)),
                ('traveler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='accounts.traveler')),
            ],
        ),
    ]
