# Generated by Django 4.0.6 on 2022-10-23 19:36

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_traveler_avatar_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city_code', models.CharField(default='0', max_length=5)),
                ('season_start', models.DateField()),
                ('season_end', models.DateField()),
                ('famous_for', multiselectfield.db.fields.MultiSelectField(choices=[('food', ' Food'), ('history', ' History'), ('sport', ' Sport'), ('clubs', ' Night life'), ('shopping', ' Shopping')], max_length=33)),
                ('info', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_date', models.DateField()),
                ('return_date', models.DateField()),
                ('budget', models.CharField(choices=[('limitless', ' No limit'), ('budget', ' On a budget'), ('regular', ' Regular')], default='regular', max_length=50)),
                ('point_of_interest', multiselectfield.db.fields.MultiSelectField(choices=[('food', ' Food'), ('history', ' History'), ('sport', ' Sport'), ('clubs', ' Night life'), ('shopping', ' Shopping')], max_length=33)),
                ('on_season', models.BooleanField(default=False)),
                ('traveler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='accounts.traveler')),
            ],
        ),
    ]
