# Generated by Django 4.0.6 on 2022-10-05 20:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='budget',
            field=models.CharField(choices=[(None, ' No limit'), ('budget', ' On a budget'), ('history', ' Regular')], max_length=50),
        ),
        migrations.AlterField(
            model_name='preference',
            name='point_of_interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(None, ' I dont care'), ('food', ' Food'), ('history', ' History'), ('sport', ' Sport'), ('clubs', ' Night life'), ('shopping', ' Shopping')], max_length=38),
        ),
    ]
