# Generated by Django 4.0.6 on 2022-10-06 09:34

from django.db import migrations, models
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_preference_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('season_start', models.DateField()),
                ('season_end', models.DateField()),
                ('famous_for', multiselectfield.db.fields.MultiSelectField(choices=[('food', ' Food'), ('history', ' History'), ('sport', ' Sport'), ('clubs', ' Night life'), ('shopping', ' Shopping')], max_length=33)),
                ('info', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='preference',
            name='budget',
            field=models.CharField(choices=[('limitless', ' No limit'), ('budget', ' On a budget'), ('regular', ' Regular')], max_length=50),
        ),
        migrations.AlterField(
            model_name='preference',
            name='point_of_interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('food', ' Food'), ('history', ' History'), ('sport', ' Sport'), ('clubs', ' Night life'), ('shopping', ' Shopping')], max_length=33),
        ),
    ]
