# Generated by Django 4.0.6 on 2022-10-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_trip_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
