# Generated by Django 4.0.6 on 2022-10-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_trips_alter_preference_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='city_code',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='preference',
            name='budget',
            field=models.CharField(choices=[('limitless', ' No limit'), ('budget', ' On a budget'), ('regular', ' Regular')], default='regular', max_length=50),
        ),
    ]
