# Generated by Django 4.0.6 on 2022-11-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='city_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
